In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array(([[5,6],[7,8]]))
C=A+B
D=A-B
E=A*B
F=np.dot(A,B)
ATranspose=A.T
print("Addition:")
print(C)
print("\n Substraction")
print(D)
print("\n Element wise Multiplication:")
print(E)
print("\n Matrix Multiplication")
print(F)
print("\n transpose")
print(ATranspose)


Addition:
[[ 6  8]
 [10 12]]

 Substraction
[[-4 -4]
 [-4 -4]]

 Element wise Multiplication:
[[ 5 12]
 [21 32]]

 Matrix Multiplication
[[19 22]
 [43 50]]

 transpose
[[1 3]
 [2 4]]


In [8]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(x)
ncomponents=2
x_reconstructed=np.dot(U[:,:ncomponents],np.dot(np.diag(S[:ncomponents]),VT[:ncomponents:]))
print("original matrix")
print(x)
print("\n Reconstructed matrix (with reduced dimensions:")
print(x_reconstructed)

original matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reconstructed matrix (with reduced dimensions:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
